stages:
  - build
  - test

variables:
  exist_version: "6.0.1"  

# image: existdb/existdb:$exist_version

build:
  stage: build
  # build expath package via ant
  script:
    - ant xar-local
    - docker pull existdb/existdb:$exist_version 
    - docker create  --name exist-ci -p 8080:8080 existdb/existdb:$exist_version 
    - docker cp ./build/*.xar exist-ci:exist/autodeploy
    - docker start exist-ci

#  see https://docs.cypress.io/guides/continuous-integration/gitlab-ci#Worker-Jobs
test:
  image: node:latest
  stage: test
  script:
    # install dependencies
    - npm ci
    # TODO pass build image between stages / use service
    # - docker start exist-ci
    # run Cypress tests
    - npm run e2e